services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   container_name: app
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - PORT=3000
  #     - NODE_ENV=production

  db:
    image: bitnami/postgresql:17.5.0
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # - POSTGRESQL_TIMEZONE=${POSTGRESQL_TIMEZONE}
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local
